Light theme
easybuilders/easybuild-docs pull request #117
Opened 2023-02-21 20:22 UTC by branfosj

This:
* adds a light theme
* toggle selection between dark and light themes
* simplifies the dark theme to just override the changes from `slate`

2023-03-15 13:42 UTC, boegel requested changes

2023-03-15 13:42 UTC, boegel commented on docs/stylesheets/extra.css
> +  --eb-green: #8ca379;
Both the blue and green is a bit too light on a white background imho, so let's use slightly darker variants, see https://github.com/branfosj/easybuild-docs/pull/2

2023-03-15 13:48 UTC, boegel commented
@branfosj Looks like CodeSpell found a couple of (new) problems, let's tackle those in a separate PR?
```
Error: ./docs/release-notes.md:7711: extermal ==> external, extremal
Error: ./docs/release-notes.md:9147: Pytho ==> Python
Error: ./docs/release-notes.md:12488: Pilon ==> Pylon, Pillion
Error: ./docs/release-notes.md:23614: Oger ==> Ogre
Codespell found one or more problems
```

2023-03-18 13:21 UTC, branfosj commented
@boegel I've fixed two spelling mistakes in 734c5cd, but I also suggest we skip spell checking the release notes (see #125)

2023-03-19 12:13 UTC, boegel approved these changes

2023-03-19 12:13 UTC, merged