port using-easybuild page to MarkDown
easybuilders/easybuild-docs pull request #12
Opened 2022-10-26 19:18 UTC by boegel

2022-10-29 10:10 UTC, orbsmiv requested changes

2022-11-03 11:34 UTC, orbsmiv commented
@boegel I'll update this PR with the changes we've made to the internal linking system so that it's consistent with the other current PRs. I'll pop it on "draft" for now but please feel free to overrule if you want to get it merged and mop the links up later!

2022-11-04 22:59 UTC, orbsmiv commented on docs/using-easybuild.md
> +This is a crucial design aspect, since the dependency resolution mechanism (see [robot]()) relies upon this convention.
Resolved by d65acbd

2022-11-05 10:40 UTC, boegel commented
> @boegel I'll update this PR with the changes we've made to the internal linking system so that it's consistent with the other current PRs. I'll pop it on "draft" for now but please feel free to overrule if you want to get it merged and mop the links up later!

Makes sense to me, thanks for the effort!

2022-11-05 23:41 UTC, orbsmiv commented
@branfosj I've looked through the whole page and also checked each link. The autorefs links, (e.g. `mkdocs_autorefs.plugin: using-easybuild.md: Could not find cross-reference target '[basic_usage_help]'`) refer to headers that will be in the auto-generated _version_specific_ files. I've created an issue (c.f. #24) to log these as and when they crop-up, although I think that we should add a placeholder file to hold all of the link-names whilst the script to generated the actual content is being written.

2022-11-06 09:40 UTC, branfosj approved these changes

2022-11-06 09:40 UTC, merged