Revised "Common Toolchains"
easybuilders/easybuild-docs pull request #149
Opened 2023-05-09 14:40 UTC by deniskristak

Revised "Common Toolchains" page + added a graph that explains Toolchains interdependence.
Also added a dependency "Mermaid" as it creates nice diagrams.

2023-05-09 14:41 UTC, deniskristak commented
@boegel  where should I fit info about `CUDA`?

2023-05-10 08:12 UTC, boegel requested changes

2023-05-10 08:12 UTC, boegel commented on docs/common-toolchains.md
> +```
improved graph:

``` mermaid
graph LR
  A[GCCCore] --> |binutils| B[GCC];
  A --> |binutils| C[iccifort]
  B --> |OpenMPI| E[gompi];
  C --> |impi| F[iimpi];
  B --> |FlexiBLAS + FFTW| D[gfbf];
  D --> |OpenMPI| G[foss];
  E --> |FlexiBLAS + FFTW| G[foss];
  F --> |imkl| H[intel];
```

2023-05-11 07:43 UTC, boegel commented on docs/common-toolchains.md
> +```
* should have different graph for old/new toolchains
* iccifort should be intel-compilers in recent toolchains
* iimkl subtoolchain is missing in intel/2022b and newer

2023-05-15 12:06 UTC, deniskristak commented
https://github.com/easybuilders/easybuild-docs/issues/150

2023-05-23 18:12 UTC, boegel requested changes

2023-05-23 18:12 UTC, boegel commented on docs/common-toolchains.md
> +that explain the differences between the generations going back to `2021a`.
```suggestion
that explain the differences between the generations going back to the `2020b` version of the `foss` and `intel` toolchains.

2023-05-23 18:15 UTC, boegel approved these changes

2023-05-23 18:15 UTC, merged