port Common toolchains page to MarkDown
easybuilders/easybuild-docs pull request #15
Opened 2022-10-27 13:25 UTC by orbsmiv

2022-10-28 10:26 UTC, orbsmiv commented on docs/common-toolchains.md
> +    Please see the [List of known toolchains](version-specific/eb-list-toolchains.md#list-of-known-toolchains) for how to obtain a listing of
I've added links in this section that point at content within the auto-generated `version-specific` directory. I've taken the placeholders from the current docs' pages but is this the correct thing to do? Obviously these placeholders don't yet exist as we're deliberately not editing any content in this directory.

2022-10-28 22:51 UTC, orbsmiv commented on docs/common-toolchains.md
> +    Please see the [List of known toolchains](version-specific/eb-list-toolchains.md#list-of-known-toolchains) for how to obtain a listing of
Resolved by 9ef3db1

2022-10-29 10:19 UTC, orbsmiv commented
Need to update internal headers, moving the --commands to the next line, where required

2022-11-05 09:56 UTC, branfosj requested changes

2022-11-05 09:56 UTC, branfosj commented on docs/common-toolchains.md
> +| `2022a` | Jun'22   | 2.38       | 11.3.0 | 2022.1.0          | 2021.6.0    | 2022.1.0    |
```suggestion
| `2020a` | May '20   | 2.34       | 9.3.0  | 2020.1.217        | 2019.7.217  | 2020.1.217  |
| `2020b` | Nov '20   | 2.35       | 10.2.0 | 2020.4.304        | 2019.9.304  | 2020.4.304  |
| `2021a` | May '21   | 2.36.1     | 10.3.0 | 2021.2.0          | 2021.2.0    | 2021.2.0    |
| `2021b` | Oct '21   | 2.37       | 11.2.0 | 2021.4.0          | 2021.4.0    | 2021.4.0    |
| `2022a` | Jun '22   | 2.38       | 11.3.0 | 2022.1.0          | 2021.6.0    | 2022.1.0    |
```

2022-11-05 09:56 UTC, branfosj commented on docs/common-toolchains.md
> +    toolchain, please see [Available toolchain options (by toolchain)](version-specific/toolchain-opts.md).
```suggestion
## More information about toolchains

Please see the [List of known toolchains](version-specific/eb-list-toolchains.md) for how to obtain a listing of
the currently known toolchains.

For a detailed listing of the compiler options available with each
toolchain, please see [Available toolchain options (by toolchain)](version-specific/toolchain-opts.md).
```

2022-11-05 09:57 UTC, branfosj approved these changes

2022-11-05 09:58 UTC, merged