port Generating container recipes & images page to Markdown
easybuilders/easybuild-docs pull request #17
Opened 2022-10-28 12:24 UTC by orbsmiv

2022-10-29 10:18 UTC, orbsmiv commented
Need to update internal headers, moving the --commands to the next line, where required

2022-11-05 09:46 UTC, branfosj requested changes

2022-11-05 09:46 UTC, branfosj commented on docs/containers.md
> +    - Python 2.6 or 2.7
```suggestion
    - Python 2.7 or 3.6+
```

2022-11-05 09:46 UTC, branfosj commented on docs/containers.md
> +(see [Overall prefix path][prefix].
```suggestion
(see [Overall prefix path][prefix]).
```

2022-11-05 09:46 UTC, branfosj commented on docs/containers.md
> +For Singularity containers (see [Type of container recipe/image to generate][containers_cfg_type])),
```suggestion
For Singularity containers (see [Type of container recipe/image to generate][containers_cfg_type]),
```

2022-11-05 09:47 UTC, branfosj approved these changes

2022-11-05 09:48 UTC, merged