Update hooks page to include undocumented hooks, as well as new ones.
easybuilders/easybuild-docs pull request #208
Opened 2023-08-09 09:40 UTC by XavierCS-dev

- Includes failure hooks, as well as `build_and_install_loop` hooks
- Detail information about hook parameters.
- Correct some small typos.
- I am unsure about the `postiter` hook and what it does, and whether it even has pre and post variations

2023-08-09 13:08 UTC, branfosj requested changes

2023-08-09 13:10 UTC, branfosj commented
Notes:
* `postiter` hooks were partially added in https://github.com/easybuilders/easybuild-framework/pull/2813, but only become available to use with https://github.com/easybuilders/easybuild-framework/pull/4316
* `fail` hooks added in https://github.com/easybuilders/easybuild-framework/pull/4315
* `build_and_install_loop` hooks added in https://github.com/easybuilders/easybuild-framework/pull/4304
* `single_extension` hooks added in https://github.com/easybuilders/easybuild-framework/pull/4193

2023-08-10 08:03 UTC, XavierCS-dev commented
Not sure why it is saying the changes aren't addressed?

2023-08-31 07:15 UTC, boegel approved these changes

2023-08-31 16:37 UTC, merged