document `pre_run_shell_cmd_hook` and `post_run_shell_cmd_hook`
easybuilders/easybuild-docs pull request #210
Opened 2023-08-31 19:22 UTC by boegel

2023-09-01 08:08 UTC, boegel commented
`markdownlint` isn't happy, and I don't understand why, the links to the subsections work fine...

```
markdownlint-cli2 v0.7.1 (markdownlint v0.28.2)
Finding: **/*.md !docs/demos !docs/version-specific
Linting: 63 file(s)
Summary: 4 error(s)
Error: docs/hooks.md:[12](https://github.com/easybuilders/easybuild-docs/actions/runs/6046813459/job/16409066224?pr=210#step:3:13)8:3 MD051/link-fragments Link fragments should be valid [Context: "[Hook arguments](#hooks-arguments)"] https://github.com/DavidAnson/markdownlint/blob/v0.28.2/doc/md051.md
Error: docs/hooks.md:129:3 MD051/link-fragments Link fragments should be valid [Context: "[Return value of hooks](#hooks-return-value)"] https://github.com/DavidAnson/markdownlint/blob/v0.28.2/doc/md051.md
Error: docs/hooks.md:[13](https://github.com/easybuilders/easybuild-docs/actions/runs/6046813459/job/16409066224?pr=210#step:3:14)0:3 MD051/link-fragments Link fragments should be valid [Context: "[Parse hook specifics](#parse-hook-specifics)"] https://github.com/DavidAnson/markdownlint/blob/v0.28.2/doc/md051.md
Error: docs/hooks.md:277:41 MD051/link-fragments Link fragments should be valid [Context: "[Parse hook specifics](#parse-hook-specifics)"] https://github.com/DavidAnson/markdownlint/blob/v0.28.2/doc/md051.md
Error: Failed with exit code: 1
```

I'll disable [rule `MD051`](https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md) to make it happy...

2023-09-01 08:41 UTC, branfosj requested changes

2023-09-01 08:41 UTC, branfosj commented on docs/hooks.md
> +* [Parse hook specifics](#parse-hook-specifics)
```suggestion
* [Hook arguments][hooks-arguments]
* [Return value of hooks][hooks-return-value]
* [Parse hook specifics][parse-hook-specifics]
```

2023-09-01 08:41 UTC, branfosj commented on .markdownlint.yml
> +"MD051": false # Link fragments should be valid. Reports false negatives when using custom anchor for subsections.
```suggestion
```

We want to avoid this, as it should prevent us getting broken internal links. Just need to work out what the issue is.

2023-09-01 14:45 UTC, branfosj approved these changes

2023-09-01 14:45 UTC, merged

2023-09-03 08:32 UTC, boegel commented on docs/hooks.md
> +* [Parse hook specifics](#parse-hook-specifics)
Oh TIL...