RPATH on by default
easybuilders/easybuild-docs pull request #241
Opened 2024-02-07 18:51 UTC by branfosj

Documentation for https://github.com/easybuilders/easybuild-framework/pull/4448

2024-02-07 19:11 UTC, boegel requested changes

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +* Disable trace mode in a [configuration file](../configuration.md#configuration_file):
```suggestion
* Disable RPATH linking in an EasyBuild [configuration file](../configuration.md#configuration_file):
```

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +    rapth=0
typo:

```suggestion
    rpath=0
```

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +To disable RPATH output, either:
```suggestion
To disable RPATH linking, either:

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +(see [Relation to `$LD_LIBRARY_PATH`][rpath_support_LD_LIBRARY_PATH]).
```suggestion
This enhancement **does not** add any filtering of environment variables. This means `$LD_LIBRARY_PATH`
will continue to be appended by the environment module files EasyBuild generates,
unless it is configured to filter these variables (via `--filter-env-vars`).
See also [Relation to `$LD_LIBRARY_PATH`][rpath_support_LD_LIBRARY_PATH]).
```

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +The [`--rpath` option][rpath_support] is enabled by default (see [easybuild-framework PR #4448](https://github.com/easybuilders/easybuild-framework/pull/4448)). The benefits for enabling RPATH are ex
```suggestion
The [RPATH linking][rpath_support] is enabled by default in EasyBuild v5.0 (see [easybuild-framework PR #4448](https://github.com/easybuilders/easybuild-framework/pull/4448)).

The benefits for enabling RPATH are explained in [Why RPATH?][rpath_support_why].

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +## Enable `--rpath` by default {: #rpath }
```suggestion
## Enable RPATH linking by default {: #rpath }
```

2024-02-07 19:11 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +* [Enable `--rpath` by default][rpath]
```suggestion
* [Enable RPATH linking by default][rpath]
```

2024-02-08 15:53 UTC, jfgrimm commented on docs/easybuild-v5/enhancements.md
> +The [RPATH linking][rpath_support] is enabled by default in EasyBuild v5.0 (see [easybuild-framework PR #4448](https://github.com/easybuilders/easybuild-framework/pull/4448)).
```suggestion
[RPATH linking][rpath_support] is enabled by default in EasyBuild v5.0 (see [easybuild-framework PR #4448](https://github.com/easybuilders/easybuild-framework/pull/4448)).
```

2024-02-09 10:42 UTC, jfgrimm approved these changes
lgtm

2024-02-14 15:28 UTC, boegel requested changes

2024-02-14 15:28 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +See also [Relation to `$LD_LIBRARY_PATH`][rpath_support_LD_LIBRARY_PATH]).
```suggestion
unless it is configured to filter these variables (via `--filter-env-vars`,
see also [Relation to `$LD_LIBRARY_PATH`][rpath_support_LD_LIBRARY_PATH]).
```

2024-02-14 15:29 UTC, boegel approved these changes

2024-02-14 15:30 UTC, merged