document `download_instructions` enhancements in EasyBuild 5.0
easybuilders/easybuild-docs pull request #243
Opened 2024-02-21 12:51 UTC by branfosj

See
* https://github.com/easybuilders/easybuild-easyconfigs/pull/19881
* https://github.com/easybuilders/easybuild-framework/pull/4459

2024-03-04 11:46 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +how to obtain sources that are not directly downloadable. In EasyBuild 5, we require that easyconfigs specify these
That's not actually entirely true, we only require this in the easyconfigs test suite, *not* in EasyBuild itself...

That's big difference, so we should reword this imho...

2024-03-13 15:42 UTC, boegel requested changes

2024-03-13 15:42 UTC, boegel commented on docs/easybuild-v5/enhancements.md
> +repository to require that all easyconfig PR specify these (see [easybuild-easyconfigs PR #19881](https://github.com/easybuilders/easybuild-easyconfigs/pull/19881)).
```suggestion
repository to require that all easyconfigs for which sources can not be downloaded automatically must specify these
(see [easybuild-easyconfigs PR #19881](https://github.com/easybuilders/easybuild-easyconfigs/pull/19881)).

2025-01-13 09:07 UTC, boegel commented
@branfosj This will need some love after things go restructured in #289...

2025-01-13 09:27 UTC, branfosj commented
> @branfosj This will need some love after things go restructured in #289...

Done

2025-03-20 00:40 UTC, lexming commented on docs/easybuild-v5/enhancements.md
> +## Require `download_instructions` to be specified {: require_download_instructions }
```suggestion
## Require `download_instructions` for non-public sources {: require_download_instructions }
```

2025-03-20 00:40 UTC, lexming commented on docs/easybuild-v5/enhancements.md
> +[`download_instructions`][download_instructions] is used in easyconfigs to specify instructions, or information, on
```suggestion
[`download_instructions`][download_instructions] is a new easyconfig parameter
in EasyBuild 5.0 used to specify instructions, or information, on
```

2025-03-20 00:40 UTC, lexming commented on docs/easybuild-v5/enhancements.md
> +repository to require that all easyconfigs for which sources can not be downloaded automatically must specify these
```suggestion
how to obtain software sources that are not directly downloadable. This is
usually the case for licensed software without public sources. In EasyBuild 5,
we've updated the testsuite for our `easybuild-easyconfigs` repository to
require that all its easyconfigs must specify the download instructions
of any non-public sources in them
```

2025-03-20 00:40 UTC, lexming commented on docs/easybuild-v5/enhancements.md
> +- [Require `download_instructions` to be specified][require_download_instructions]
```suggestion
- [Require `download_instructions` for non-public sources][require_download_instructions]
```

2025-03-20 00:45 UTC, lexming commented on docs/easybuild-v5/enhancements.md
> +(see [easybuild-easyconfigs PR #19881](https://github.com/easybuilders/easybuild-easyconfigs/pull/19881)).
```suggestion
usually the case for licensed software without public sources.

We've updated the testsuite for our `easybuild-easyconfigs` repository to
require that all its easyconfigs must specify the download instructions
of any non-public sources in them
(see [easybuild-easyconfigs PR #19881](https://github.com/easybuilders/easybuild-easyconfigs/pull/19881)).
```

2025-03-20 00:49 UTC, lexming approved these changes

2025-03-20 00:50 UTC, merged