use mkdocstrings to generate API docs (WIP)
easybuilders/easybuild-docs pull request #79
Opened 2022-11-27 17:20 UTC by branfosj

Uses:
* [`mkdocstings`](https://mkdocstrings.github.io/)

Based on the example at <https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages>. Expects to find the easybuild framework checked out in `src`.

Issue:
* `py2.py` caused this to blowup
* do `cd src/easybuild/tools/py2vs3 && mv py2.py{,.orig} && ln -s py3.py py2.py`

2022-12-03 18:39 UTC, boegel commented
While playing with this, I hit the following error when building the docs with `mkdocs build`:

```
ERROR    -  Error reading page 'api/easybuild/index.md': 'easyconfigs'
Traceback (most recent call last):
  File "/Users/kehoste/Library/Python/3.9/lib/python/site-packages/griffe/loader.py", line 473, in _member_parent
    return module[parent_parts]
  File "/Users/kehoste/Library/Python/3.9/lib/python/site-packages/griffe/mixins.py", line 27, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
KeyError: 'easyconfigs'
```

This is somehow caused by having all `easybuild-*` code repos (+ `vsc-install` and `vsc-base`) listed in my `$PYTHONPATH`:

```
$ echo $PYTHONPATH
/Users/kehoste/work/easybuild-easyconfigs:/Users/kehoste/work/easybuild-easyblocks:/Users/kehoste/work/easybuild-framework:/Users/kehoste/work/vsc-install/lib:/Users/kehoste/work/vsc-base/lib
```

Workaround is to just wipe `$PYTHONPATH` while running `mkdocs build`:

```
PYTHONPATH= mkdocs build
```

2023-01-04 16:03 UTC, boegel requested changes

2023-01-04 16:38 UTC, branfosj commented on mkdocs.yml
> +          paths: [src]
We can tackle that in a follow on to this

2023-01-04 16:51 UTC, boegel commented on mkdocs.yml
> +          paths: [src]
opened #88 to follow up on this

2023-01-04 16:51 UTC, merged